Repository civilcode/acme-platform, pull requests merged in 2018-10, with the labels that each got.

#70 Upgrade to Distillery 2.0
  Dockerfile
  config/prod.exs
  config/staging.exs
  mix.exs
  mix.lock
  rel/commands/migrate.sh
  rel/config.exs
  rel/config/config.exs
Labels: type:chore, wf:review

#75 chore: Move envrc -> env
  .gitignore
  bin/setup.config
  env.sample
  envrc.sample
Labels: type:chore, wf:review

#85 Run migrations explicitly on CircleCI
  .circleci/config.yml
Labels: type:chore

#84 Remove all generated comments
  .formatter.exs
  apps/magasin/config/config.exs
  apps/magasin/lib/magasin.ex
  apps/magasin_web/config/config.exs
  apps/magasin_web/lib/magasin_web.ex
  apps/magasin_web/lib/magasin_web/application.ex
  apps/magasin_web/lib/magasin_web/channels/user_socket.ex
  apps/magasin_web/lib/magasin_web/endpoint.ex
  apps/magasin_web/lib/magasin_web/router.ex
  apps/magasin_web/lib/magasin_web/views/error_helpers.ex
  apps/magasin_web/lib/magasin_web/views/error_view.ex
  apps/magasin_web/lib/magasin_web/views/layout_view.ex
  apps/magasin_web/lib/magasin_web/views/page_view.ex
  apps/magasin_web/mix.exs
  apps/magasin_web/test/magasin_web/views/error_view_test.exs
  apps/magasin_web/test/support/conn_case.ex
  config/config.exs
  config/dev.exs
  config/test.exs
  rel/config.exs
Labels: type:chore

#80 Introduce a makefile for tasks
  Makefile
  README.md
  bin/deploy_staging
  bin/heroku.docker.build
  bin/heroku.docker.run
  bin/heroku.docker.stop
  deploy/local/Makefile
  deploy/staging/Makefile
  guides/app/docker-deployment.md
Labels: type:chore, wf:review

#41 Upgrade to Elixir v1.7.1
  .circleci/config.yml
  Dockerfile
  Dockerfile.dev
  apps/magasin_web/lib/magasin_web/endpoint.ex
  apps/master_proxy/test/master_proxy/plug_test.exs
  apps/master_proxy/test/test_helper.exs
Labels: type:chore, wf:in-progress
