Repository civilcode/acme-platform, pull requests merged in 2019-01, with the labels that each got.

#114 Add observer support
  Makefile
  docker-compose.yml
  guides/app/docker-development.md
Labels: type:chore

#119 Setup release tags
  Dockerfile
  README.md
  apps/magasin/mix.exs
  apps/magasin_web/lib/magasin_web/templates/layout/app.html.slim
  apps/magasin_web/lib/magasin_web/views/layout_view.ex
  apps/magasin_web/mix.exs
  apps/master_proxy/mix.exs
  config/config.exs
  config/dev.exs
  config/test.exs
  deploy/staging/Makefile
  heroku.yml
  mix.exs
  rel/config.exs
Labels: wf:review

#120 Add iterations to the "task" feature template
  .github/ISSUE_TEMPLATE/feature---task.md
Labels: type:chore, wf:review

#112 Add docs to the release
  Dockerfile
  Makefile
  apps/magasin_web/lib/magasin_web/endpoint.ex
  apps/magasin_web/lib/magasin_web/templates/layout/app.html.slim
  mix.exs
  mix.lock
Labels: wf:review
