Repository civilcode/acme-platform, pull requests merged in 2019-02, with the labels that each got.

#123 Install CivilCredo
  apps/magasin/tag_wip.ex
  mix.exs
  mix.lock
Labels: type:chore, wf:review

#125 Extract config in makefiles
  Makefile
  deploy/local/Makefile
  deploy/staging/Makefile
Labels: type:chore, wf:review

#126 Configure docs
  Dockerfile
  mix.exs
Labels: type:chore

#127 Extract CivilCode
  apps/magasin/coveralls.json
  apps/magasin/lib/civilcode/aggregate.ex
  apps/magasin/lib/civilcode/application_service.ex
  apps/magasin/lib/civilcode/business_rule_violation.ex
  apps/magasin/lib/civilcode/command.ex
  apps/magasin/lib/civilcode/domain_event.ex
  apps/magasin/lib/civilcode/domain_primitive.composite.ex
  apps/magasin/lib/civilcode/domain_primitive.ex
  apps/magasin/lib/civilcode/entity.ex
  apps/magasin/lib/civilcode/repository.ex
  apps/magasin/lib/civilcode/repository_error.ex
  apps/magasin/lib/civilcode/result.ex
  apps/magasin/lib/civilcode/validation.ex
  apps/magasin/mix.exs
  mix.lock
  rel/config.exs
Labels: type:chore

#124 Add a inline guide for Issues/PRs
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/feature---task.md
Labels: wf:review

#134 Convert DB volume to a mount
  .gitignore
  apps/magasin_web/assets/package-lock.json
  docker-compose.yml
Labels: type:chore

#139 Add upgrade guide
  guides/elixir/dependencies.md
  guides/elixir/upgrades.md
Labels: type:chore
